/*
 * logo.h
 *
 *  Created on: Feb 4, 2018
 *      Author: Neo
 */

#ifndef LOGO_H_
#define LOGO_H_





#endif /* LOGO_H_ */

// this file generated by Image2GLCD
extern const unsigned char logo[];
